apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: zoidbot
  labels:
    app: postgres
    environment: development
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    app: postgres