apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backend
  namespace: CloudToLocalLLM
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: api-backend
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: CloudToLocalLLM
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: web
          resources:
            requests:
              memory: "128Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "250m"