# Flutter Builder Docker Compose Configuration
# Provides a containerized Flutter build environment with automatic SDK updates

services:
  # Flutter Builder Service - For building web applications with latest Flutter SDK
  flutter-builder:
    build:
      context: .
      dockerfile: config/docker/Dockerfile.flutter-builder
    image: cloudtolocalllm-flutter-builder:latest
    container_name: cloudtolocalllm-flutter-builder
    volumes:
      # Mount source code
      - .:/home/flutter/workspace:rw
      # Persistent Flutter SDK cache
      - flutter-sdk-cache:/opt/flutter
      # Persistent pub cache for faster builds
      - flutter-pub-cache:/opt/flutter/.pub-cache
    environment:
      - FLUTTER_HOME=/opt/flutter
      - PUB_CACHE=/opt/flutter/.pub-cache
      - FLUTTER_WEB_USE_SKIA=false
      - FLUTTER_WEB_AUTO_DETECT=true
    working_dir: /home/flutter/workspace
    networks:
      - flutter-build-network
    profiles:
      - build
    command: /bin/bash -c "
      echo 'Flutter Builder Container Started';
      echo 'Available commands:';
      echo '  - /home/flutter/update-flutter.sh (Update Flutter SDK)';
      echo '  - /home/flutter/build-web.sh (Build web application)';
      echo '  - flutter --version (Check Flutter version)';
      echo '  - flutter doctor (Check Flutter installation)';
      tail -f /dev/null
      "

  # Flutter Build Runner - One-shot service for automated builds
  flutter-build-runner:
    build:
      context: .
      dockerfile: config/docker/Dockerfile.flutter-builder
    image: cloudtolocalllm-flutter-builder:latest
    container_name: cloudtolocalllm-flutter-build-runner
    volumes:
      # Mount source code
      - .:/home/flutter/workspace:rw
      # Persistent Flutter SDK cache
      - flutter-sdk-cache:/opt/flutter
      # Persistent pub cache for faster builds
      - flutter-pub-cache:/opt/flutter/.pub-cache
    environment:
      - FLUTTER_HOME=/opt/flutter
      - PUB_CACHE=/opt/flutter/.pub-cache
      - FLUTTER_WEB_USE_SKIA=false
      - FLUTTER_WEB_AUTO_DETECT=true
    working_dir: /home/flutter/workspace
    networks:
      - flutter-build-network
    profiles:
      - build-runner
    command: /bin/bash -c "
      echo 'Starting automated Flutter build process...';
      /home/flutter/update-flutter.sh;
      /home/flutter/build-web.sh;
      echo 'Build process completed';
      "

networks:
  flutter-build-network:
    driver: bridge
    name: cloudtolocalllm-flutter-build

volumes:
  flutter-sdk-cache:
    name: cloudtolocalllm-flutter-sdk-cache
  flutter-pub-cache:
    name: cloudtolocalllm-flutter-pub-cache
