version: '3.8'

services:
  # Web application service
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: cloudtolocalllm-webapp
    container_name: cloudtolocalllm-webapp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health_internal || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Postfix Mail Server for direct email sending
  # WARNING: Ensuring email deliverability with a self-hosted MTA is complex.
  # Requires proper rDNS (PTR), SPF, DKIM, DMARC, and an IP with good reputation.
  # Port 25 outbound must not be blocked by your VPS provider.
  postfix-mail:
    image: boky/postfix:latest
    container_name: cloudtolocalllm-postfix-mail
    restart: always
    environment:
      - "HOSTNAME=mail.cloudtolocalllm.online"
      - "DOMAIN=cloudtolocalllm.online"
      - "ALLOWED_SENDER_DOMAINS=cloudtolocalllm.online"
      - "NETWORK_INTERFACE=eth0"
      - "RELAYHOST="
      - "MYNETWORKS=127.0.0.0/8 172.16.0.0/12 192.168.0.0/16"
      - "DKIM_DOMAINS=cloudtolocalllm.online"
      - "DKIM_SELECTOR=mail"
      - "DKIM_KEY_PATH=/etc/opendkim/keys/cloudtolocalllm.online/mail.private"
      - "DKIM_AUTOGENERATE=true"
    volumes:
      - ./config/dkim:/etc/opendkim/keys/cloudtolocalllm.online:ro 
    ports:
      - "2500:25"
    cap_add:
      - NET_ADMIN

  # Certbot for SSL certificates
  certbot:
    image: certbot/certbot
    container_name: cloudtolocalllm-certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - ./scripts/certbot_permissions_hook.sh:/opt/certbot_permissions_hook.sh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: |
      /bin/sh -c '
        trap exit TERM;
        # Initialize certbot directories with proper permissions
        mkdir -p /var/www/certbot/.well-known/acme-challenge;
        chmod -R 755 /var/www/certbot;
        mkdir -p /etc/letsencrypt/live /etc/letsencrypt/archive;
        chmod -R 755 /etc/letsencrypt;
        echo "Attempting initial certificate acquisition...";
        certbot certonly --webroot -w /var/www/certbot --email christopher.maltais@gmail.com --agree-tos --no-eff-email -d cloudtolocalllm.online -d www.cloudtolocalllm.online -d app.cloudtolocalllm.online --deploy-hook "/opt/certbot_permissions_hook.sh" || echo "Initial certonly command failed or no certs due for renewal.";
        echo "Initial cert attempt/check done. Starting renewal loop.";
        while :; do
          certbot renew --quiet --webroot -w /var/www/certbot --deploy-hook "/opt/certbot_permissions_hook.sh";
          sleep 12h & wait $${!};
        done;
      '
