name: cloudtolocalllm
description: A new Flutter project.
publish_to: 'none'
version: 1.3.2+202505092025

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  uuid: ^4.2.1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  http: ^1.1.0
  path: '>=1.8.2 <2.0.0'
  process_run: ^0.13.3+1
  system_tray: ^2.0.3
  window_manager: ^0.3.9
  win32: ^5.0.9
  logging: ^1.2.0 # Used by admin_control_daemon Dart server
  js: '>=0.6.7 <0.7.0'
  crypto: ^3.0.3
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0
  flutter_secure_storage: ^9.0.0
  args: ^2.4.2

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/CloudToLocalLLM_logo.jpg
