name: cloudtolocalllm
description: A new Flutter project.
publish_to: 'none'
version: 1.3.1+202405051630

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.5
  uuid: ^4.2.1
  path_provider: ^2.1.1
  shared_preferences: ^2.0.15
  url_launcher: ^6.2.2
  http: ^1.3.0
  path: ^1.8.3
  process_run: ^1.2.4
  system_tray: ^0.1.1
  window_manager: ^0.4.3
  win32: ^5.0.0
  logging: ^1.2.0
  js: ^0.6.7
  crypto: ^3.0.2
  device_info_plus: ^10.0.0
  package_info_plus: ^8.3.0
  flutter_secure_storage: ^9.2.4
  args: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/CloudToLocalLLM_logo.jpg
