name: cloudtolocalllm
description: A new Flutter project.
publish_to: 'none'
version: 1.2.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  uuid: ^4.2.1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  http: ^1.2.0
  path: ^1.8.3
  process_run: ^0.13.1
  system_tray: ^0.1.1
  window_manager: ^0.3.7
  win32: ^5.0.0
  logging: ^1.2.0
  js: ^0.7.2
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/CloudToLocalLLM_logo.jpg
