apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-backend-sa
  namespace: zoidbot
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: Replace=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    app: api-backend
    app.kubernetes.io/name: api-backend
    app.kubernetes.io/instance: api-backend
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: zoidbot
    app.kubernetes.io/managed-by: argocd
    environment: production
    tier: backend
    component: api
    zoidbot.com/app-tier: backend
    zoidbot.com/app-type: api
    zoidbot.com/app-environment: production
imagePullSecrets:
  - name: acr-credentials
  - name: regcred