apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./shared/base/web-frontend
images:
  - name: ghcr.io/cloudtolocalllm-online/ghcr.io/cloudtolocalllm-online/cloudtolocalllm/web
    newTag: main-1ebf1f7843b7278fc86964ccca37b9268a244160
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: web
        namespace: cloudtolocalllm
      spec:
        replicas: 1
        template:
          spec:
            containers:
              - name: web
                resources:
                  requests:
                    memory: "128Mi"
                    cpu: "10m"
                  limits:
                    memory: "256Mi"
                    cpu: "250m"