apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../deployments/app_base/api-backend
images:
  - name: imrightguycloudtolocalllm.azurecr.io/api-backend
    newTag: main-78c38d20dddcd3d29dae2dc25874cdf685eef141-api-backend
patches:
  - path: ../../../deployments/overlays/managed/env-patch.yaml
  - path: ../../../deployments/overlays/managed/scaling.yaml
