apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../deployments/app_base/api-backend
images:
  - name: imrightguycloudtolocalllm.azurecr.io/api-backend
    newTag: main-1c7c5d499e27cd28ea47a3ef7978f42d18018237-api-backend
patches:
  - path: ../../../deployments/overlays/managed/env-patch.yaml
  - path: ../../../deployments/overlays/managed/scaling.yaml
