# The docker-compose configuration for the CloudToLocalLLM monitoring services

services:
  netdata:
    image: netdata/netdata:latest
    container_name: cloudtolocalllm_monitor
    hostname: cloudtolocalllm
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - netdata-config:/etc/netdata
      - netdata-lib:/var/lib/netdata
      - netdata-cache:/var/cache/netdata
    environment:
      - NETDATA_CLAIM_TOKEN=${NETDATA_CLAIM_TOKEN:-}
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
      - NETDATA_CLAIM_ROOMS=${NETDATA_CLAIM_ROOMS:-}
    networks:
      - cloudllm-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:19999/api/v1/info"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  netdata-config:
  netdata-lib:
  netdata-cache:

networks:
  cloudllm-network:
    external: true
  # webnet:
  #   driver: bridge 