version: '3'

services:
  admin-daemon:
    build:
      context: ../../
      dockerfile: config/docker/Dockerfile.admin_daemon
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../:/opt/cloudtolocalllm
    restart: unless-stopped
    environment:
      - PORT=9001
    user: "1000:1000" # Run as non-root user for security and compatibility 