# Basic Docker Compose for FusionAuth App and PostgreSQL Database
version: '3.8'

volumes:
  fusionauth_config:
  fusionauth_postgres_data:

networks:
  fusionauth_net:
    driver: bridge

services:
  # FusionAuth Application
  fusionauth:
    image: fusionauth/fusionauth-app:latest
    container_name: cloudtolocalllm-fusionauth-app
    restart: unless-stopped
    ports:
      - "9011:9011" # FusionAuth UI/API port
    environment:
      # IMPORTANT: Set strong, unique passwords in your actual deployment environment!
      # Use environment variables or secrets management on the VPS.
      DATABASE_URL: jdbc:postgresql://postgres:5432/fusionauth
      DATABASE_ROOT_USERNAME: postgres           # User for initial DB connection/setup
      DATABASE_ROOT_PASSWORD: password           # Password for initial DB connection/setup
      DATABASE_USERNAME: fusionauth              # User FusionAuth will use to connect
      DATABASE_PASSWORD: password                # Password FusionAuth will use to connect
      FUSIONAUTH_APP_MEMORY: 512M                # Adjust as needed
      FUSIONAUTH_APP_RUNTIME_MODE: production    # Use 'development' for testing if needed
      FUSIONAUTH_APP_URL: http://localhost:9011 # URL used by FusionAuth internally/emails (Adjust if needed for VPS domain)
      SEARCH_ENGINE_TYPE: database             # Use database search initially (no Elasticsearch)
      # Required for initial setup - CHANGE THIS IN PRODUCTION
      FUSIONAUTH_APP_SETUP_PASSWORD: fusionauth_setup_password 
    depends_on:
      - postgres
    volumes:
      - fusionauth_config:/usr/local/fusionauth/config
    networks:
      - fusionauth_net

  # PostgreSQL Database for FusionAuth
  postgres:
    image: postgres:13-alpine # Or a later supported version
    container_name: cloudtolocalllm-fusionauth-postgres
    restart: unless-stopped
    ports:
      - "5432:5432" # Standard PostgreSQL port
    environment:
      # IMPORTANT: Set strong, unique passwords in your actual deployment environment!
      POSTGRES_USER: postgres      # Superuser for setup
      POSTGRES_PASSWORD: password  # Superuser password for setup
      # Optional: You can pre-create the DB and user if preferred
      # POSTGRES_DB: fusionauth
      # FUSIONAUTH_DB_USER: fusionauth
      # FUSIONAUTH_DB_PASSWORD: password
    volumes:
      - fusionauth_postgres_data:/var/lib/postgresql/data
    networks:
      - fusionauth_net 