version: '3.8'

services:
  tunnel:
    build:
      context: .
      dockerfile: Dockerfile.tunnel
    networks:
      - llm-network

  cloud:
    image: node:20
    working_dir: /app
    depends_on:
      tunnel:
        condition: service_started
    networks:
      - llm-network
    volumes:
      - ./cloud:/app
      - ./setup_cloud.sh:/app/setup_cloud.sh
    command: /bin/bash /app/setup_cloud.sh
    ports:
      - "3456:3456"

  webapp:
    build:
      context: ../..
      dockerfile: config/docker/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../../build/web:/usr/share/nginx/html:ro
    networks:
      - llm-network
    restart: unless-stopped

networks:
  llm-network:
    driver: bridge
