version: '3.8'

services:
  # Authentication service
  auth:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: cloudtolocalllm-auth
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth
      - POSTGRES_HOST=postgres
      - JWT_SECRET=your-secret-key
    depends_on:
      - postgres
    volumes:
      - ./auth_service:/app
      - /app/node_modules
    networks:
      - auth_net

  # PostgreSQL database for auth service
  postgres:
    image: postgres:13-alpine
    container_name: cloudtolocalllm-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - auth_net

  # Admin web interface
  admin-ui:
    build:
      context: ./admin-ui
      dockerfile: Dockerfile
    container_name: cloudtolocalllm-admin-ui
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - auth
    networks:
      - auth_net

volumes:
  postgres_data:

networks:
  auth_net:
    driver: bridge 