---
# CloudToLocalLLM Ansible Inventory
all:
  children:
    build_hosts:
      children:
        windows_builders:
          hosts:
            localhost:
              ansible_connection: local
              ansible_python_interpreter: "{{ ansible_playbook_python }}"
              platform: windows
              build_types:
                - windows_desktop
                - portable_zip
        
        linux_builders:
          hosts:
            wsl_ubuntu:
              ansible_connection: local
              ansible_python_interpreter: /usr/bin/python3
              platform: linux
              wsl_distro: Ubuntu
              build_types:
                - aur
                - appimage
                - flatpak
                - deb
                - web
    
    deployment_targets:
      children:
        vps_servers:
          hosts:
            cloudtolocalllm_vps:
              ansible_host: app.cloudtolocalllm.online
              ansible_user: cloudllm
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
              platform: linux
              project_dir: /opt/cloudtolocalllm
              docker_compose_file: docker-compose.multi.yml
              services:
                - webapp
                - api-backend
                - streaming-proxy
        
        github_releases:
          hosts:
            github_api:
              ansible_connection: local
              ansible_python_interpreter: "{{ ansible_playbook_python }}"
              github_owner: imrightguy
              github_repo: CloudToLocalLLM
              github_token: "{{ vault_github_token }}"

  vars:
    # Project Configuration
    project_name: CloudToLocalLLM
    project_root: "{{ playbook_dir }}/.."
    
    # Version Management
    version_files:
      - pubspec.yaml
      - assets/version.json
      - lib/shared/lib/version.dart
      - lib/config/app_config.dart
    
    # Build Configuration
    flutter_channel: stable
    flutter_version: latest
    
    # Docker Configuration
    docker_registry: docker.io
    docker_namespace: cloudtolocalllm
    
    # Security
    container_user: proxyuser
    container_uid: 1001
    container_gid: 1001
