name: auth_service
description: Authentication service for CloudToLocalLLM
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  postgres: ^3.5.6
  dart_jsonwebtoken: ^3.1.1
  logging: ^1.2.0
  crypto: ^3.0.3
  uuid: ^4.2.1
  shelf_cors_headers: ^0.1.4
  meta: ^1.9.1
  http: ^1.4.0
  # path: ^1.8.0
  jose: ^0.3.3
  dotenv: ^4.2.0
  args: ^2.4.2

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
