apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer-sa
  namespace: zoidbot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployer-role
rules:
  - apiGroups:
      ["", "apps", "networking.k8s.io", "batch", "rbac.authorization.k8s.io"]
    resources:
      - deployments
      - services
      - ingresses
      - pods
      - pods/log
      - configmaps
      - secrets
      - statefulsets
      - persistentvolumeclaims
      - jobs
      - serviceaccounts
      - roles
      - rolebindings
      - networkpolicies
      - endpoints
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployer-binding
subjects:
  - kind: ServiceAccount
    name: deployer-sa
    namespace: zoidbot
roleRef:
  kind: ClusterRole
  name: deployer-role
  apiGroup: rbac.authorization.k8s.io
