apiVersion: v1
kind: Secret
metadata:
  name: cloudtolocalllm-secrets
  namespace: cloudtolocalllm
type: Opaque
stringData:
  postgres-user: |-
    ${POSTGRES_USER}
  postgres-password: |-
    ${POSTGRES_PASSWORD}
  postgres-auth-password: |-
    ${POSTGRES_AUTH_PASSWORD}
  jwt-secret: |-
    ${JWT_SECRET}
  auth0-domain: |-
    ${AUTH0_DOMAIN}
  auth0-audience: |-
    ${AUTH0_AUDIENCE}
  auth0-client-id: |-
    ${AUTH0_CLIENT_ID}
  auth0-client-secret: |-
    ${AUTH0_CLIENT_SECRET}
  stripe-test-secret-key: |-
    ${STRIPE_TEST_SECRET_KEY}
  stripe-test-publishable-key: |-
    ${STRIPE_TEST_PUBLISHABLE_KEY}
  stripe-test-webhook-secret: |-
    ${STRIPE_TEST_WEBHOOK_SECRET}
  stripe-live-secret-key: |-
    ${STRIPE_LIVE_SECRET_KEY}
  stripe-live-publishable-key: |-
    ${STRIPE_LIVE_PUBLISHABLE_KEY}
  stripe-live-webhook-secret: |-
    ${STRIPE_LIVE_WEBHOOK_SECRET}
  sentry-dsn: |-
    ${SENTRY_DSN}

