name: admin_control_daemon
description: A Dart-based daemon for managing services and admin actions.
version: 0.0.1
# repository: https://github.com/your_org/admin_control_daemon

environment:
  sdk: '>=3.0.0 <4.0.0'

# dependencies:
#   shelf: ^1.4.0
#   shelf_router: ^1.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0 