import 'package:flutter/material.dart';

import '../services/departure_photos_service.dart';
import '../theme/app_colors.dart';
import '../theme/app_spacing.dart';
import '../widgets/immo_app_bar.dart';
import '../widgets/loading_state.dart';
import '../widgets/error_state.dart';
import '../widgets/empty_state.dart';
import '../widgets/status_badge.dart';

/// Lists the move-out / move-in (état des lieux) photos and photo requests
/// generated by the PlexFlow webhooks.
class DeparturePhotosScreen extends StatefulWidget {
  const DeparturePhotosScreen({super.key});

  @override
  State<DeparturePhotosScreen> createState() => _DeparturePhotosScreenState();
}

class _DeparturePhotosScreenState extends State<DeparturePhotosScreen> {
  bool _isLoading = true;
  Object? _lastError;
  List<Map<String, dynamic>> _photos = [];
  String? _filter; // null = all, 'departure', 'arrival'

  @override
  void initState() {
    super.initState();
    _fetch();
  }

  Future<void> _fetch() async {
    setState(() {
      _isLoading = true;
      _lastError = null;
    });
    try {
      final photos =
          await DeparturePhotosService.instance.list(eventType: _filter);
      if (!mounted) return;
      setState(() {
        _photos = photos;
        _isLoading = false;
      });
    } catch (e) {
      if (!mounted) return;
      setState(() {
        _lastError = e;
        _isLoading = false;
      });
    }
  }

  void _setFilter(String? value) {
    setState(() => _filter = value);
    _fetch();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: const ImmoAppBar(title: 'Photos départ / arrivée'),
      body: Column(
        children: [
          _buildFilterBar(),
          Expanded(child: _buildBody()),
        ],
      ),
    );
  }

  Widget _buildFilterBar() {
    return Padding(
      padding: const EdgeInsets.symmetric(
          horizontal: AppSpacing.lg, vertical: AppSpacing.sm),
      child: Row(
        children: [
          _filterChip('Tous', null),
          const SizedBox(width: AppSpacing.sm),
          _filterChip('Départs', 'departure'),
          const SizedBox(width: AppSpacing.sm),
          _filterChip('Arrivées', 'arrival'),
        ],
      ),
    );
  }

  Widget _filterChip(String label, String? value) {
    final selected = _filter == value;
    return ChoiceChip(
      label: Text(label),
      selected: selected,
      onSelected: (_) => _setFilter(value),
      selectedColor: AppColors.primary.withValues(alpha: 0.15),
      labelStyle: TextStyle(
        fontSize: 13,
        fontWeight: FontWeight.w500,
        color: selected ? AppColors.primary : AppColors.textSecondary,
      ),
    );
  }

  Widget _buildBody() {
    if (_isLoading) return const ListSkeleton(showSearchBar: false);
    if (_lastError != null) {
      return ErrorState(error: _lastError!, onRetry: _fetch);
    }
    if (_photos.isEmpty) {
      return const EmptyState(
        title: 'Aucune photo',
        description:
            'Les demandes de photos de départ/arrivée apparaîtront ici dès qu\'un locataire part ou arrive.',
        icon: Icons.photo_library_outlined,
      );
    }

    return RefreshIndicator(
      onRefresh: _fetch,
      child: ListView.builder(
        padding: const EdgeInsets.all(AppSpacing.lg),
        itemCount: _photos.length,
        itemBuilder: (context, index) => _photoCard(_photos[index]),
      ),
    );
  }

  Widget _photoCard(Map<String, dynamic> photo) {
    final eventType = photo['eventType'] as String? ?? 'departure';
    final isDeparture = eventType == 'departure';
    final tenantName = photo['tenantName'] as String? ?? 'Locataire inconnu';
    final notes = photo['notes'] as String?;
    final photoUrl = photo['photoUrl'] as String?;
    final createdAt = DateTime.tryParse(photo['createdAt'] as String? ?? '');

    return Card(
      margin: const EdgeInsets.only(bottom: AppSpacing.md),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(AppSpacing.radiusMd),
      ),
      child: Padding(
        padding: const EdgeInsets.all(AppSpacing.lg),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Icon(
                  isDeparture ? Icons.logout : Icons.login,
                  size: 20,
                  color: isDeparture ? AppColors.warning : AppColors.success,
                ),
                const SizedBox(width: 8),
                Expanded(
                  child: Text(
                    tenantName,
                    style: const TextStyle(
                      fontSize: 15,
                      fontWeight: FontWeight.w600,
                      color: AppColors.textPrimary,
                    ),
                  ),
                ),
                StatusBadge(
                  label: isDeparture ? 'Départ' : 'Arrivée',
                  variant:
                      isDeparture ? BadgeVariant.warning : BadgeVariant.success,
                ),
              ],
            ),
            if (createdAt != null) ...[
              const SizedBox(height: 6),
              Text(
                _formatDate(createdAt),
                style: const TextStyle(
                    fontSize: 12, color: AppColors.textSecondary),
              ),
            ],
            if (photoUrl != null && photoUrl.isNotEmpty) ...[
              const SizedBox(height: AppSpacing.md),
              ClipRRect(
                borderRadius: BorderRadius.circular(AppSpacing.radiusSm),
                child: Image.network(
                  photoUrl,
                  height: 160,
                  width: double.infinity,
                  fit: BoxFit.cover,
                  errorBuilder: (_, __, ___) => Container(
                    height: 160,
                    color: AppColors.surfaceVariant,
                    alignment: Alignment.center,
                    child: const Icon(Icons.broken_image_outlined,
                        color: AppColors.textMuted),
                  ),
                ),
              ),
            ] else ...[
              const SizedBox(height: AppSpacing.sm),
              const Row(
                children: [
                  Icon(Icons.hourglass_empty,
                      size: 14, color: AppColors.textMuted),
                  SizedBox(width: 6),
                  Text(
                    'En attente de photos',
                    style: TextStyle(
                      fontSize: 12,
                      fontStyle: FontStyle.italic,
                      color: AppColors.textMuted,
                    ),
                  ),
                ],
              ),
            ],
            if (notes != null && notes.isNotEmpty) ...[
              const SizedBox(height: AppSpacing.sm),
              Text(
                notes,
                style: const TextStyle(
                    fontSize: 12, color: AppColors.textSecondary),
              ),
            ],
          ],
        ),
      ),
    );
  }

  String _formatDate(DateTime date) {
    const months = [
      'janv.', 'févr.', 'mars', 'avr.', 'mai', 'juin',
      'juill.', 'août', 'sept.', 'oct.', 'nov.', 'déc.'
    ];
    final d = date.toLocal();
    return '${d.day} ${months[d.month - 1]} ${d.year} · '
        '${d.hour.toString().padLeft(2, '0')}:${d.minute.toString().padLeft(2, '0')}';
  }
}
