apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/deployments/web.yaml
  - ../../base/deployments/api-backend.yaml
  - ../../base/deployments/streaming-proxy.yaml
  - ../../base/deployments/postgres.yaml
  - ../../base/deployments/redis.yaml
  - ../../base/services/web.yaml
  - ../../base/services/api-backend.yaml
  - ../../base/services/streaming-proxy.yaml
  - ../../base/services/postgres.yaml
  - ../../base/services/redis.yaml
  - ../../base/configmaps/main-config.yaml
  - ../../base/configmaps/redis.yaml
  - ../../base/configmaps/streaming-proxy-configmap.yaml
  # - ../../base/secrets/acr-credentials.yaml # Secrets are managed externally/manually usually
  - ../../base/network-policies.yaml
  - ../../base/cloudflared-egress.yaml
  - cloudflared-tunnel.yaml

patches:
  - path: env-patch.yaml
  - path: scaling.yaml
  - path: resource-patch.yaml