const swaggerJsdoc = require('swagger-jsdoc');

const options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'ImmoGestion API',
      version: '1.0.0',
      description: 'Quebec leasing automation engine API. Manage buildings, units, leads, leases, visits, employees, communications, documents, SMS campaigns, and analytics.',
      contact: {
        name: 'ImmoGestion',
        email: 'support@immogestion.ca',
      },
    },
    servers: [
      {
        url: 'http://localhost:3000',
        description: 'Local development server',
      },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
          description: 'JWT access token obtained from /api/auth/login',
        },
      },
      schemas: {
        ErrorResponse: {
          type: 'object',
          properties: {
            success: { type: 'boolean', example: false },
            error: {
              type: 'object',
              properties: {
                message: { type: 'string' },
                code: { type: 'string' },
              },
            },
          },
        },
        SuccessResponse: {
          type: 'object',
          properties: {
            success: { type: 'boolean', example: true },
            data: {},
            message: { type: 'string' },
          },
        },
        PaginationMeta: {
          type: 'object',
          properties: {
            total: { type: 'integer' },
            page: { type: 'integer' },
            limit: { type: 'integer' },
            totalPages: { type: 'integer' },
            hasMore: { type: 'boolean' },
          },
        },
        Building: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            name: { type: 'string' },
            address: { type: 'string' },
            city: { type: 'string' },
            province: { type: 'string', example: 'QC' },
            postalCode: { type: 'string' },
            totalUnits: { type: 'integer' },
            unitsAvailable: { type: 'integer' },
            ownerId: { type: 'string', format: 'uuid' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Unit: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            buildingId: { type: 'string', format: 'uuid' },
            unitNumber: { type: 'string' },
            type: { type: 'string', enum: ['studio', '1br', '2br', '3br', '4br', 'other'] },
            rentAmount: { type: 'number' },
            sqft: { type: 'integer' },
            isAvailable: { type: 'boolean' },
            bedrooms: { type: 'integer' },
            bathrooms: { type: 'integer' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Lead: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            firstName: { type: 'string' },
            lastName: { type: 'string' },
            email: { type: 'string', format: 'email' },
            phone: { type: 'string' },
            status: { type: 'string', enum: ['new', 'contacted', 'interested', 'viewing_scheduled', 'application_submitted', 'approved', 'rejected', 'leased', 'inactive'] },
            source: { type: 'string' },
            buildingId: { type: 'string', format: 'uuid' },
            unitId: { type: 'string', format: 'uuid' },
            notes: { type: 'string' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Lease: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            unitId: { type: 'string', format: 'uuid' },
            buildingId: { type: 'string', format: 'uuid' },
            tenantId: { type: 'string', format: 'uuid' },
            startDate: { type: 'string', format: 'date' },
            endDate: { type: 'string', format: 'date' },
            rentAmount: { type: 'number' },
            status: { type: 'string', enum: ['draft', 'active', 'expired', 'terminated'] },
            signedAt: { type: 'string', format: 'date-time' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Visit: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            leadId: { type: 'string', format: 'uuid' },
            unitId: { type: 'string', format: 'uuid' },
            employeeId: { type: 'string', format: 'uuid' },
            dateTime: { type: 'string', format: 'date-time' },
            durationMinutes: { type: 'integer', minimum: 1, maximum: 1440 },
            status: { type: 'string', enum: ['scheduled', 'confirmed', 'in_progress', 'completed', 'cancelled', 'no_show'] },
            tenantConfirmed: { type: 'boolean' },
            employeeConfirmed: { type: 'boolean' },
            morningOfSent: { type: 'boolean' },
            outcome: { type: 'string', enum: ['interesse', 'pas_interesse', 'no_show'], nullable: true },
            reasonCode: { type: 'string', enum: ['tenant_request', 'tenant_conflict', 'host_unavailable', 'access_issue', 'weather', 'tenant_no_show', 'employee_declined', 'no_response', 'other'], nullable: true },
            completedAt: { type: 'string', format: 'date-time', nullable: true },
            cancelledAt: { type: 'string', format: 'date-time', nullable: true },
            noShowAt: { type: 'string', format: 'date-time', nullable: true },
            rescheduledAt: { type: 'string', format: 'date-time', nullable: true },
            notes: { type: 'string' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Employee: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            firstName: { type: 'string' },
            lastName: { type: 'string' },
            email: { type: 'string', format: 'email' },
            phone: { type: 'string' },
            role: { type: 'string', enum: ['admin', 'manager', 'agent', 'maintenance'] },
            isActive: { type: 'boolean' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Document: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            name: { type: 'string' },
            type: { type: 'string' },
            category: { type: 'string' },
            url: { type: 'string', format: 'uri' },
            buildingId: { type: 'string', format: 'uuid' },
            unitId: { type: 'string', format: 'uuid' },
            leaseId: { type: 'string', format: 'uuid' },
            uploadedBy: { type: 'string', format: 'uuid' },
            status: { type: 'string', enum: ['pending', 'approved', 'rejected'] },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Schedule: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            employeeId: { type: 'string', format: 'uuid' },
            dayOfWeek: { type: 'integer', minimum: 0, maximum: 6 },
            startTime: { type: 'string', example: '09:00' },
            endTime: { type: 'string', example: '17:00' },
            isAvailable: { type: 'boolean' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Communication: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            leadId: { type: 'string', format: 'uuid', nullable: true },
            employeeId: { type: 'string', format: 'uuid', nullable: true },
            type: { type: 'string', enum: ['email', 'phone', 'sms', 'fb_messenger'] },
            direction: { type: 'string', enum: ['inbound', 'outbound'] },
            subject: { type: 'string' },
            content: { type: 'string' },
            attachments: { type: 'array', items: { oneOf: [{ type: 'string' }, { type: 'object' }] } },
            status: { type: 'string' },
            metadata: { type: 'object', additionalProperties: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        CommunicationThread: {
          type: 'object',
          properties: {
            leadId: { type: 'string', format: 'uuid' },
            contactId: { type: 'string', format: 'uuid' },
            contactName: { type: 'string' },
            contactPhone: { type: 'string' },
            contactInitials: { type: 'string' },
            qualificationState: { type: 'string', nullable: true },
            qualificationReasonCode: { type: 'string', nullable: true },
            qualificationReasonNote: { type: 'string', nullable: true },
            bookingState: {
              type: 'string',
              nullable: true,
              enum: ['unbooked', 'booking_pending', 'scheduled', 'confirmed', 'in_progress', 'completed', 'cancelled', 'no_show', 'reschedule_requested'],
            },
            bookingReasonCode: { type: 'string', nullable: true },
            bookingStateUpdatedAt: { type: 'string', format: 'date-time', nullable: true },
            messageCount: { type: 'integer' },
            lastMessageAt: { type: 'string', format: 'date-time' },
            firstSeenAt: { type: 'string', format: 'date-time', nullable: true },
            firstResponseAt: { type: 'string', format: 'date-time', nullable: true },
            firstResponseDelayMinutes: { type: 'integer', nullable: true },
            coordinationState: {
              type: 'string',
              enum: ['message_only', 'awaiting_employee_confirmation', 'awaiting_tenant_confirmation', 'scheduled', 'confirmed', 'in_progress', 'completed_interested', 'completed_not_interested', 'completed_no_show', 'cancelled', 'follow_up_required'],
            },
            latestVisit: {
              type: 'object',
              nullable: true,
              properties: {
                id: { type: 'string', format: 'uuid' },
                status: { type: 'string' },
                outcome: { type: 'string', nullable: true },
                reasonCode: { type: 'string', nullable: true },
                completedAt: { type: 'string', format: 'date-time', nullable: true },
                cancelledAt: { type: 'string', format: 'date-time', nullable: true },
                noShowAt: { type: 'string', format: 'date-time', nullable: true },
                rescheduledAt: { type: 'string', format: 'date-time', nullable: true },
                dateTime: { type: 'string', format: 'date-time', nullable: true },
                tenantConfirmed: { type: 'boolean' },
                employeeConfirmed: { type: 'boolean' },
                morningOfSent: { type: 'boolean' },
              },
            },
            lastMessage: { $ref: '#/components/schemas/Communication' },
            messages: {
              type: 'array',
              items: { $ref: '#/components/schemas/Communication' },
            },
          },
        },
        SmsTemplate: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            name: { type: 'string' },
            body: { type: 'string' },
            category: { type: 'string' },
            variables: { type: 'array', items: { type: 'string' } },
            isActive: { type: 'boolean' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        SmsCampaign: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            name: { type: 'string' },
            templateId: { type: 'string', format: 'uuid' },
            status: { type: 'string', enum: ['draft', 'active', 'executing', 'completed', 'failed'] },
            recipientCount: { type: 'integer' },
            sentCount: { type: 'integer' },
            failedCount: { type: 'integer' },
            scheduledAt: { type: 'string', format: 'date-time' },
            executedAt: { type: 'string', format: 'date-time' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Notification: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            userId: { type: 'string', format: 'uuid' },
            type: { type: 'string' },
            title: { type: 'string' },
            message: { type: 'string' },
            isRead: { type: 'boolean' },
            createdAt: { type: 'string', format: 'date-time' },
          },
        },
      },
    },
    tags: [
      { name: 'Auth', description: 'Authentication and user management' },
      { name: 'Buildings', description: 'Building and unit management' },
      { name: 'Employees', description: 'Employee management and assignments' },
      { name: 'Leads', description: 'Lead management and pipeline' },
      { name: 'Leases', description: 'Lease management and signing' },
      { name: 'Visits', description: 'Visit scheduling and tracking' },
      { name: 'Documents', description: 'Document management and approval' },
      { name: 'Schedules', description: 'Employee schedule management' },
      { name: 'Communications', description: 'Communication logging and activity feed' },
      { name: 'Marketplace', description: 'Lead inbox and unified messages/visit workflow' },
      { name: 'SMS Webhooks', description: 'Twilio SMS webhook endpoints' },
      { name: 'SMS Campaigns', description: 'SMS template and campaign management' },
      { name: 'Facebook', description: 'Facebook Messenger webhook endpoints' },
      { name: 'Analytics', description: 'Dashboard and reporting analytics' },
      { name: 'Notifications', description: 'User notification management' },
      { name: 'Observation Results', description: 'Reviewed workflow observation intake and triage' },
      { name: 'Tenant Confirmation', description: 'Tenant lease confirmation via SMS link' },
      { name: 'Admin', description: 'Admin operations (seed data)' },
    ],
  },
  apis: ['./src/routes/*.js', './src/server.js', './src/config/swagger.js'],
};

const swaggerSpec = swaggerJsdoc(options);

module.exports = swaggerSpec;
