name: cloudtolocalllm_bridge
description: CloudToLocalLLM Desktop Bridge - Secure bridge for local Ollama to cloud service
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # UI and theming
  cupertino_icons: ^1.0.6
  material_color_utilities: ^0.8.0
  
  # System tray integration
  system_tray: ^2.0.3
  tray_manager: ^0.2.0
  window_manager: ^0.3.7
  
  # Authentication
  auth0_flutter: ^1.4.0
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  
  # Networking
  web_socket_channel: ^2.4.0
  http: ^1.1.0
  dio: ^5.3.2
  
  # Configuration and storage
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  yaml: ^3.1.2
  
  # State management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Utilities
  logger: ^2.0.2+1
  package_info_plus: ^4.2.0
  url_launcher: ^6.2.1
  desktop_notifications: ^0.6.3
  
  # JSON and serialization
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
