apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../deployments/app_base/web-frontend
images:
  - name: imrightguycloudtolocalllm.azurecr.io/web
    newTag: main-cf6b7f1b7685b4cae2aa9ff14a5795701306d806
patches:
  - path: ../../../deployments/overlays/managed/env-patch.yaml
  - path: ../../../deployments/overlays/managed/scaling.yaml
