apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../deployments/app_base/web-frontend
images:
  - name: ghcr.io/cloudtolocalllm-online/cloudtolocalllm/web
    newTag: main-8d91e61c261508376f5bc9443f4e1a47130586ae
patches:
  - path: ../../../deployments/overlays/managed/env-patch.yaml
  - path: ../../../deployments/overlays/managed/scaling.yaml
