apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../deployments/app_base/web-frontend
images:
  - name: imrightguycloudtolocalllm.azurecr.io/web
    newTag: main-c4dcfe17f4d6a69eb01bebf29a9ad241991d08a6
patches:
  - path: ../../../deployments/overlays/managed/env-patch.yaml
  - path: ../../../deployments/overlays/managed/scaling.yaml
