tunnel: 62da6c19-947b-4bf6-acad-100a73de4e0d
ingress:
  - hostname: app.cloudtolocalllm.online
    service: http://127.0.0.1:3100
  - hostname: api.cloudtolocalllm.online
    service: http://127.0.0.1:3100
  - service: http_status:404
