name: cloudtolocalllm_chat
description: CloudToLocalLLM Chat Application - Main user interface for authentication and chat functionality
version: 3.2.1
publish_to: 'none'

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # Shared components
  cloudtolocalllm_shared:
    path: ../shared

  # UI and Navigation
  cupertino_icons: ^1.0.8
  go_router: ^15.1.2

  # Authentication
  openid_client: ^0.4.9
  url_launcher: ^6.3.1

  # HTTP and Web
  http: ^1.2.2
  web: ^1.1.1

  # App Information
  package_info_plus: ^8.1.1

  # File System
  path: ^1.9.1

  # State Management
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
