tunnel: ee26f195-904b-4406-a8ae-9265c9971004
credentials-file: /etc/cloudflared/creds.json

ingress:
  - hostname: app.cloudtolocalllm.online
    service: http://web:8080
  - hostname: api.cloudtolocalllm.online
    service: http://api-backend:8080
  - hostname: cloudtolocalllm.online
    service: http://web:8080
  - service: http_status:404
